package com.fatron.network_module.models.response.packages

data class Package(
    val action_type_id: Any?,
    val amount: Int?,
    val banner_image_id: Any?,
    val created_at: String?,
    val description: String?,
    val end_date: String?,
    val external_code: Any?,
    val flasher_image_id: Any?,
    val id: Int?,
    val is_active: Int?,
    val is_linked_customers: Any?,
    val is_non_linked_customers: Any?,
    val max_age: Int?,
    val min_age: Int?,
    val name: String?,
    val number_of_action: Any?,
    val number_of_transaction: Any?,
    val promocode: Any?,
    val promotion_type_id: Int?,
    val reference_code: String?,
    val reset_frequency: Any?,
    val start_date: String?,
    val status_id: Int?,
    val tenant_id: String?,
    val terms_and_conditions: Any?,
    val updated_at: String?,
    val valid_days: Int?,
    val validity_check_type: Int?,
    val week_days: Any?,
    val promotion_media: PromoMedia?
)